[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor -T ./partitions.csv --erase-parts otadata"

[env]
CC = "<your path>\\.espressif\\tools\\riscv32-esp-elf\\esp-13.2.0_20240530\\riscv32-esp-elf\\bin\\riscv32-esp-elf-gcc"
AR = "<your path>\\.espressif\\tools\\riscv32-esp-elf\\esp-13.2.0_20240530\\riscv32-esp-elf\\bin\\riscv32-esp-elf-ar"

ESP_DEVICE_TYPE="esp32c6"
ESP_DEVICE_NAME="esp32c6-example"
ESP_DEVICE_VERSION="0.1.1"

MENDER_CLIENT_WIFI_SSID="Your ssid"
MENDER_CLIENT_WIFI_PSK="Your psk"
MENDER_CLIENT_URL="https://hosted.mender.io"
MENDER_CLIENT_TENANT_TOKEN="1bur7DrhLfluaDsc6_By--gRrw636A5J0rq4bhxnEfw"

ESP_LOG="INFO"
ESP_WIFI_CONFIG_PHY_ENABLE_USB = "false"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]